cc_library(
    name = "many_attrs",
    srcs = glob(["file*.cpp"]),
    hdrs = ["header.h"],
    copts = ["-Wall"],
    defines = ["MY_DEFINE=1"],
    includes = ["include"],
    linkopts = ["-lm"],
    visibility = ["//visibility:public"],
)
